### PR TITLE
Add SQLite 3.33.0 for CPython

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://www.sqlite.org/releaselog/3_33_0.html

### CODE REVIEW

**Comment by erlend-aasland** [comment]
@zooba, would you mind reviewing this?

**Comment by zooba** [comment]
Thanks. Ultimately, the review that I need to do is download and check in the source code myself to make sure it's unmodified, so I'll just push it directly.

(Also, my GitHub notifications is a dumpster fire, so I never see anything. Better to ping me on bugs.python.org)

**Comment by erlend-aasland** [comment]
> Thanks. Ultimately, the review that I need to do is download and check in the source code myself to make sure it's unmodified, so I'll just push it directly.

Ok.
 
> (Also, my GitHub notifications is a dumpster fire, so I never see anything. Better to ping me on bugs.python.org)

Got it!

**Comment by zooba** [comment]
> to make sure it's unmodified

FWIW, this is a terrible pain, because they list their hashes as "sha3" without clarifying which length, and the hash for the .zip file doesn't match any of the ones I can generate 😆 

Luckily they list the hashes for the main source file separately and those check out.

**Comment by zooba** [comment]
Okay, my tag is up: https://github.com/python/cpython-source-deps/tree/sqlite-3.33.0.0

In theory, your diff should collapse to nothing now, but I'm not sure how/when GitHub will figure that out.

**Pull request closed without merging**
