### PR TITLE
Add SQLite 3.30.1 for CPython bpo-38380.

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://sqlite.org/releaselog/3_30_0.html
https://sqlite.org/releaselog/3_30_1.html

### CODE REVIEW

**Comment by erlend-aasland** [comment]
FYI, upgraded to sqlite 3.30.1.

**Comment by ambv** [comment]
Thanks! ✨ 🍰 ✨  

cc @zooba

**Comment by erlend-aasland** [comment]
@ambv, @zooba: I forgot to push the tag. Could one of you please tag this with `sqlite-3.30.1.0`, so the Windows installer builder can find it.

(I can't create a PR just for the tag, and I can't push the tag to this repo.)

**Comment by zooba** [comment]
I can't get the tag right now - having github.com access issues. @zware ?

**Comment by zware** [comment]
Should be done.

**Pull request merged**
