### PR TITLE
cpython-source-deps:libffi

### PR DESCRIPTION
**Pull request by ossdev07**
adding code of libffi to support AARCH64 architecture

Signed-off-by: ossdev07 <ossdev@puresoftware.com>

### CODE REVIEW

**Comment by ossdev07** [comment]
@paulmon pls have a look on this PR

**Comment by paulmon** [comment]
@ossdev07 I believe the Python project is waiting for a tested official release of libffi to take in libffi changes.

@zooba

**Comment by ossdev07** [comment]
@zooba @paulmon  : have you had a chance to review this PR and is libffi testing done or not?

**Comment by zooba** [comment]
We want to keep this as close as possible to the libffi sources, with the only exceptions being when we _need_ to take a patch to fix a CPython issue and have also submitted that patch upstream.

On that basis, this PR is not something we will review ourselves. And since Python 3.8 is locking down (which is the first to include libffi out of this repo), we should probably tag the sources used so that the build is reproducible before taking changes for 3.9. I'm not going to do that from an airport, but will take a look once I'm back at work next week.

Once we've tagged the build for 3.8, then we can take a new version of libffi's sources. I'm not clear, but I suspect this PR isn't a complete update from libffi. It needs to be merged into libffi first, and then we can take a complete update of their next release.

**Comment by ossdev07** [comment]
> We want to keep this as close as possible to the libffi sources, with the only exceptions being when we _need_ to take a patch to fix a CPython issue and have also submitted that patch upstream.
> 
> On that basis, this PR is not something we will review ourselves. And since Python 3.8 is locking down (which is the first to include libffi out of this repo), we should probably tag the sources used so that the build is reproducible before taking changes for 3.9. I'm not going to do that from an airport, but will take a look once I'm back at work next week.
> 
> Once we've tagged the build for 3.8, then we can take a new version of libffi's sources. I'm not clear, but I suspect this PR isn't a complete update from libffi. It needs to be merged into libffi first, and then we can take a complete update of their next release.

@zooba did you get chance to have a look on this PR ..

**Comment by ossdev07** [comment]
Changes are already merged in following commit 
https://github.com/python/cpython-source-deps/commit/35a5081d073058159e8db96c43029f88c1da501a

Now This PR is not required hence closing ..

**Pull request closed without merging**
